#!/bin/bash
python convert_train_code.py --input_file train-00000_problem_info_0.json
python convert_train_code.py --input_file train-00000_problem_info_4.json
python convert_train_code.py --input_file train-00000_problem_info_11.json
python convert_train_code.py --input_file train-00000_problem_info_16.json
python convert_train_code.py --input_file train-00000_problem_info_19.json
python convert_train_code.py --input_file train-00000_problem_info_25.json
python convert_train_code.py --input_file train-00000_problem_info_26.json
python convert_train_code.py --input_file train-00000_problem_info_28.json
python convert_train_code.py --input_file train-00000_problem_info_29.json
python convert_train_code.py --input_file train-00001_problem_info_2.json
python convert_train_code.py --input_file train-00001_problem_info_5.json
python convert_train_code.py --input_file train-00001_problem_info_15.json
python convert_train_code.py --input_file train-00001_problem_info_26.json
python convert_train_code.py --input_file train-00001_problem_info_30.json
python convert_train_code.py --input_file train-00002_problem_info_14.json
python convert_train_code.py --input_file train-00002_problem_info_15.json
python convert_train_code.py --input_file train-00002_problem_info_18.json
python convert_train_code.py --input_file train-00002_problem_info_21.json
python convert_train_code.py --input_file train-00002_problem_info_22.json
python convert_train_code.py --input_file train-00003_problem_info_1.json
python convert_train_code.py --input_file train-00003_problem_info_6.json
python convert_train_code.py --input_file train-00003_problem_info_7.json
python convert_train_code.py --input_file train-00003_problem_info_8.json
python convert_train_code.py --input_file train-00003_problem_info_9.json
python convert_train_code.py --input_file train-00003_problem_info_13.json
python convert_train_code.py --input_file train-00003_problem_info_16.json
python convert_train_code.py --input_file train-00003_problem_info_18.json
python convert_train_code.py --input_file train-00003_problem_info_19.json
python convert_train_code.py --input_file train-00003_problem_info_21.json
python convert_train_code.py --input_file train-00003_problem_info_24.json
python convert_train_code.py --input_file train-00004_problem_info_1.json
python convert_train_code.py --input_file train-00004_problem_info_2.json
python convert_train_code.py --input_file train-00004_problem_info_4.json
python convert_train_code.py --input_file train-00004_problem_info_6.json
python convert_train_code.py --input_file train-00004_problem_info_8.json
python convert_train_code.py --input_file train-00004_problem_info_12.json
python convert_train_code.py --input_file train-00004_problem_info_13.json
python convert_train_code.py --input_file train-00004_problem_info_15.json
python convert_train_code.py --input_file train-00004_problem_info_17.json
python convert_train_code.py --input_file train-00004_problem_info_18.json
python convert_train_code.py --input_file train-00004_problem_info_20.json
python convert_train_code.py --input_file train-00004_problem_info_21.json
python convert_train_code.py --input_file train-00004_problem_info_25.json
python convert_train_code.py --input_file train-00005_problem_info_3.json
python convert_train_code.py --input_file train-00005_problem_info_10.json
python convert_train_code.py --input_file train-00005_problem_info_13.json
python convert_train_code.py --input_file train-00005_problem_info_19.json
python convert_train_code.py --input_file train-00005_problem_info_21.json
python convert_train_code.py --input_file train-00005_problem_info_23.json
python convert_train_code.py --input_file train-00005_problem_info_24.json
python convert_train_code.py --input_file train-00005_problem_info_27.json
python convert_train_code.py --input_file train-00005_problem_info_28.json
python convert_train_code.py --input_file train-00005_problem_info_30.json
python convert_train_code.py --input_file train-00006_problem_info_0.json
python convert_train_code.py --input_file train-00006_problem_info_2.json
python convert_train_code.py --input_file train-00006_problem_info_4.json
python convert_train_code.py --input_file train-00006_problem_info_5.json
python convert_train_code.py --input_file train-00006_problem_info_6.json
python convert_train_code.py --input_file train-00006_problem_info_21.json
python convert_train_code.py --input_file train-00006_problem_info_23.json
python convert_train_code.py --input_file train-00006_problem_info_27.json
python convert_train_code.py --input_file train-00006_problem_info_28.json
python convert_train_code.py --input_file train-00007_problem_info_0.json
python convert_train_code.py --input_file train-00007_problem_info_6.json
python convert_train_code.py --input_file train-00007_problem_info_14.json
python convert_train_code.py --input_file train-00007_problem_info_15.json
python convert_train_code.py --input_file train-00007_problem_info_16.json
python convert_train_code.py --input_file train-00007_problem_info_17.json
python convert_train_code.py --input_file train-00007_problem_info_18.json
python convert_train_code.py --input_file train-00007_problem_info_19.json
python convert_train_code.py --input_file train-00007_problem_info_25.json
python convert_train_code.py --input_file train-00007_problem_info_28.json
python convert_train_code.py --input_file train-00007_problem_info_29.json
python convert_train_code.py --input_file train-00007_problem_info_30.json
python convert_train_code.py --input_file train-00008_problem_info_19.json
python convert_train_code.py --input_file train-00008_problem_info_21.json
python convert_train_code.py --input_file train-00008_problem_info_26.json
python convert_train_code.py --input_file train-00009_problem_info_3.json
python convert_train_code.py --input_file train-00009_problem_info_6.json
python convert_train_code.py --input_file train-00009_problem_info_7.json
python convert_train_code.py --input_file train-00009_problem_info_8.json
python convert_train_code.py --input_file train-00009_problem_info_12.json
python convert_train_code.py --input_file train-00009_problem_info_14.json
python convert_train_code.py --input_file train-00009_problem_info_15.json
python convert_train_code.py --input_file train-00009_problem_info_16.json
python convert_train_code.py --input_file train-00009_problem_info_17.json
python convert_train_code.py --input_file train-00009_problem_info_19.json
python convert_train_code.py --input_file train-00009_problem_info_20.json
python convert_train_code.py --input_file train-00009_problem_info_21.json
python convert_train_code.py --input_file train-00009_problem_info_24.json
python convert_train_code.py --input_file train-00009_problem_info_27.json
python convert_train_code.py --input_file train-00010_problem_info_7.json
python convert_train_code.py --input_file train-00010_problem_info_8.json
python convert_train_code.py --input_file train-00010_problem_info_9.json
python convert_train_code.py --input_file train-00010_problem_info_14.json
python convert_train_code.py --input_file train-00010_problem_info_15.json
python convert_train_code.py --input_file train-00010_problem_info_16.json
python convert_train_code.py --input_file train-00010_problem_info_23.json
python convert_train_code.py --input_file train-00010_problem_info_24.json
python convert_train_code.py --input_file train-00010_problem_info_26.json
python convert_train_code.py --input_file train-00010_problem_info_27.json
python convert_train_code.py --input_file train-00011_problem_info_2.json
python convert_train_code.py --input_file train-00011_problem_info_3.json
python convert_train_code.py --input_file train-00011_problem_info_5.json
python convert_train_code.py --input_file train-00011_problem_info_16.json
python convert_train_code.py --input_file train-00011_problem_info_24.json
python convert_train_code.py --input_file train-00011_problem_info_25.json
python convert_train_code.py --input_file train-00011_problem_info_26.json
python convert_train_code.py --input_file train-00012_problem_info_1.json
python convert_train_code.py --input_file train-00012_problem_info_5.json
python convert_train_code.py --input_file train-00012_problem_info_7.json
python convert_train_code.py --input_file train-00012_problem_info_14.json
python convert_train_code.py --input_file train-00012_problem_info_16.json
python convert_train_code.py --input_file train-00012_problem_info_17.json
python convert_train_code.py --input_file train-00012_problem_info_24.json
python convert_train_code.py --input_file train-00012_problem_info_25.json
python convert_train_code.py --input_file train-00013_problem_info_0.json
python convert_train_code.py --input_file train-00013_problem_info_1.json
python convert_train_code.py --input_file train-00013_problem_info_10.json
python convert_train_code.py --input_file train-00013_problem_info_11.json
python convert_train_code.py --input_file train-00013_problem_info_13.json
python convert_train_code.py --input_file train-00013_problem_info_14.json
python convert_train_code.py --input_file train-00013_problem_info_17.json
python convert_train_code.py --input_file train-00014_problem_info_4.json
python convert_train_code.py --input_file train-00014_problem_info_6.json
python convert_train_code.py --input_file train-00014_problem_info_10.json
python convert_train_code.py --input_file train-00014_problem_info_12.json
python convert_train_code.py --input_file train-00014_problem_info_14.json
python convert_train_code.py --input_file train-00014_problem_info_16.json
python convert_train_code.py --input_file train-00014_problem_info_17.json
python convert_train_code.py --input_file train-00014_problem_info_18.json
python convert_train_code.py --input_file train-00014_problem_info_20.json
python convert_train_code.py --input_file train-00014_problem_info_21.json
python convert_train_code.py --input_file train-00014_problem_info_23.json
python convert_train_code.py --input_file train-00014_problem_info_24.json
python convert_train_code.py --input_file train-00014_problem_info_25.json
python convert_train_code.py --input_file train-00014_problem_info_27.json
python convert_train_code.py --input_file train-00014_problem_info_29.json
python convert_train_code.py --input_file train-00014_problem_info_31.json
python convert_train_code.py --input_file train-00015_problem_info_6.json
python convert_train_code.py --input_file train-00015_problem_info_7.json
python convert_train_code.py --input_file train-00015_problem_info_11.json
python convert_train_code.py --input_file train-00015_problem_info_13.json
python convert_train_code.py --input_file train-00015_problem_info_18.json
python convert_train_code.py --input_file train-00015_problem_info_23.json
python convert_train_code.py --input_file train-00015_problem_info_24.json
python convert_train_code.py --input_file train-00015_problem_info_28.json
python convert_train_code.py --input_file train-00016_problem_info_2.json
python convert_train_code.py --input_file train-00016_problem_info_4.json
python convert_train_code.py --input_file train-00016_problem_info_7.json
python convert_train_code.py --input_file train-00016_problem_info_15.json
python convert_train_code.py --input_file train-00016_problem_info_21.json
python convert_train_code.py --input_file train-00016_problem_info_22.json
python convert_train_code.py --input_file train-00016_problem_info_23.json
python convert_train_code.py --input_file train-00016_problem_info_26.json
python convert_train_code.py --input_file train-00017_problem_info_0.json
python convert_train_code.py --input_file train-00017_problem_info_2.json
python convert_train_code.py --input_file train-00017_problem_info_3.json
python convert_train_code.py --input_file train-00017_problem_info_4.json
python convert_train_code.py --input_file train-00017_problem_info_6.json
python convert_train_code.py --input_file train-00017_problem_info_11.json
python convert_train_code.py --input_file train-00017_problem_info_12.json
python convert_train_code.py --input_file train-00017_problem_info_14.json
python convert_train_code.py --input_file train-00017_problem_info_17.json
python convert_train_code.py --input_file train-00017_problem_info_19.json
python convert_train_code.py --input_file train-00018_problem_info_14.json
python convert_train_code.py --input_file train-00018_problem_info_18.json
python convert_train_code.py --input_file train-00018_problem_info_19.json
python convert_train_code.py --input_file train-00018_problem_info_23.json
python convert_train_code.py --input_file train-00019_problem_info_0.json
python convert_train_code.py --input_file train-00019_problem_info_1.json
python convert_train_code.py --input_file train-00019_problem_info_2.json
python convert_train_code.py --input_file train-00019_problem_info_10.json
python convert_train_code.py --input_file train-00019_problem_info_11.json
python convert_train_code.py --input_file train-00019_problem_info_13.json
python convert_train_code.py --input_file train-00019_problem_info_15.json
python convert_train_code.py --input_file train-00019_problem_info_16.json
python convert_train_code.py --input_file train-00019_problem_info_18.json
python convert_train_code.py --input_file train-00019_problem_info_19.json
python convert_train_code.py --input_file train-00019_problem_info_21.json
python convert_train_code.py --input_file train-00019_problem_info_23.json
python convert_train_code.py --input_file train-00019_problem_info_24.json
python convert_train_code.py --input_file train-00019_problem_info_27.json
python convert_train_code.py --input_file train-00020_problem_info_10.json
python convert_train_code.py --input_file train-00020_problem_info_12.json
python convert_train_code.py --input_file train-00020_problem_info_15.json
python convert_train_code.py --input_file train-00020_problem_info_16.json
python convert_train_code.py --input_file train-00020_problem_info_17.json
python convert_train_code.py --input_file train-00020_problem_info_22.json
python convert_train_code.py --input_file train-00020_problem_info_23.json
python convert_train_code.py --input_file train-00020_problem_info_26.json
python convert_train_code.py --input_file train-00020_problem_info_27.json
python convert_train_code.py --input_file train-00021_problem_info_1.json
python convert_train_code.py --input_file train-00021_problem_info_6.json
python convert_train_code.py --input_file train-00021_problem_info_9.json
python convert_train_code.py --input_file train-00021_problem_info_11.json
python convert_train_code.py --input_file train-00021_problem_info_14.json
python convert_train_code.py --input_file train-00021_problem_info_21.json
python convert_train_code.py --input_file train-00021_problem_info_22.json
python convert_train_code.py --input_file train-00021_problem_info_24.json
python convert_train_code.py --input_file train-00022_problem_info_2.json
python convert_train_code.py --input_file train-00022_problem_info_6.json
python convert_train_code.py --input_file train-00022_problem_info_7.json
python convert_train_code.py --input_file train-00022_problem_info_8.json
python convert_train_code.py --input_file train-00022_problem_info_11.json
python convert_train_code.py --input_file train-00022_problem_info_15.json
python convert_train_code.py --input_file train-00022_problem_info_16.json
python convert_train_code.py --input_file train-00022_problem_info_17.json
python convert_train_code.py --input_file train-00022_problem_info_18.json
python convert_train_code.py --input_file train-00022_problem_info_26.json
python convert_train_code.py --input_file train-00023_problem_info_3.json
python convert_train_code.py --input_file train-00023_problem_info_5.json
python convert_train_code.py --input_file train-00023_problem_info_12.json
python convert_train_code.py --input_file train-00023_problem_info_14.json
python convert_train_code.py --input_file train-00023_problem_info_18.json
python convert_train_code.py --input_file train-00023_problem_info_19.json
python convert_train_code.py --input_file train-00023_problem_info_20.json
python convert_train_code.py --input_file train-00023_problem_info_23.json
python convert_train_code.py --input_file train-00024_problem_info_1.json
python convert_train_code.py --input_file train-00024_problem_info_7.json
python convert_train_code.py --input_file train-00024_problem_info_8.json
python convert_train_code.py --input_file train-00024_problem_info_13.json
python convert_train_code.py --input_file train-00024_problem_info_15.json
python convert_train_code.py --input_file train-00024_problem_info_19.json
python convert_train_code.py --input_file train-00024_problem_info_23.json
python convert_train_code.py --input_file train-00025_problem_info_0.json
python convert_train_code.py --input_file train-00025_problem_info_5.json
python convert_train_code.py --input_file train-00025_problem_info_9.json
python convert_train_code.py --input_file train-00025_problem_info_11.json
python convert_train_code.py --input_file train-00025_problem_info_12.json
python convert_train_code.py --input_file train-00025_problem_info_14.json
python convert_train_code.py --input_file train-00025_problem_info_15.json
python convert_train_code.py --input_file train-00025_problem_info_16.json
python convert_train_code.py --input_file train-00025_problem_info_19.json
python convert_train_code.py --input_file train-00025_problem_info_21.json
python convert_train_code.py --input_file train-00025_problem_info_22.json
python convert_train_code.py --input_file train-00025_problem_info_23.json
python convert_train_code.py --input_file train-00025_problem_info_24.json
python convert_train_code.py --input_file train-00025_problem_info_26.json
python convert_train_code.py --input_file train-00025_problem_info_28.json
python convert_train_code.py --input_file train-00025_problem_info_29.json
python convert_train_code.py --input_file train-00026_problem_info_0.json
python convert_train_code.py --input_file train-00026_problem_info_2.json
python convert_train_code.py --input_file train-00026_problem_info_3.json
python convert_train_code.py --input_file train-00026_problem_info_15.json
python convert_train_code.py --input_file train-00026_problem_info_20.json
python convert_train_code.py --input_file train-00026_problem_info_22.json
python convert_train_code.py --input_file train-00026_problem_info_24.json
python convert_train_code.py --input_file train-00026_problem_info_27.json
python convert_train_code.py --input_file train-00026_problem_info_30.json
python convert_train_code.py --input_file train-00026_problem_info_31.json
python convert_train_code.py --input_file train-00027_problem_info_1.json
python convert_train_code.py --input_file train-00027_problem_info_2.json
python convert_train_code.py --input_file train-00027_problem_info_7.json
python convert_train_code.py --input_file train-00027_problem_info_12.json
python convert_train_code.py --input_file train-00027_problem_info_14.json
python convert_train_code.py --input_file train-00027_problem_info_15.json
python convert_train_code.py --input_file train-00027_problem_info_16.json
python convert_train_code.py --input_file train-00027_problem_info_18.json
python convert_train_code.py --input_file train-00027_problem_info_24.json
python convert_train_code.py --input_file train-00028_problem_info_6.json
python convert_train_code.py --input_file train-00028_problem_info_8.json
python convert_train_code.py --input_file train-00028_problem_info_9.json
python convert_train_code.py --input_file train-00028_problem_info_17.json
python convert_train_code.py --input_file train-00028_problem_info_18.json
python convert_train_code.py --input_file train-00028_problem_info_21.json
python convert_train_code.py --input_file train-00028_problem_info_22.json
python convert_train_code.py --input_file train-00028_problem_info_27.json
python convert_train_code.py --input_file train-00029_problem_info_4.json
python convert_train_code.py --input_file train-00029_problem_info_10.json
python convert_train_code.py --input_file train-00029_problem_info_16.json
python convert_train_code.py --input_file train-00029_problem_info_17.json
python convert_train_code.py --input_file train-00029_problem_info_18.json
python convert_train_code.py --input_file train-00029_problem_info_20.json
python convert_train_code.py --input_file train-00029_problem_info_23.json
python convert_train_code.py --input_file train-00030_problem_info_8.json
python convert_train_code.py --input_file train-00030_problem_info_11.json
python convert_train_code.py --input_file train-00030_problem_info_12.json
python convert_train_code.py --input_file train-00030_problem_info_14.json
python convert_train_code.py --input_file train-00030_problem_info_17.json
python convert_train_code.py --input_file train-00030_problem_info_19.json
python convert_train_code.py --input_file train-00030_problem_info_21.json
python convert_train_code.py --input_file train-00031_problem_info_0.json
python convert_train_code.py --input_file train-00031_problem_info_3.json
python convert_train_code.py --input_file train-00031_problem_info_7.json
python convert_train_code.py --input_file train-00031_problem_info_8.json
python convert_train_code.py --input_file train-00031_problem_info_9.json
python convert_train_code.py --input_file train-00031_problem_info_10.json
python convert_train_code.py --input_file train-00031_problem_info_12.json
python convert_train_code.py --input_file train-00031_problem_info_16.json
python convert_train_code.py --input_file train-00031_problem_info_20.json
python convert_train_code.py --input_file train-00031_problem_info_22.json
python convert_train_code.py --input_file train-00031_problem_info_23.json
python convert_train_code.py --input_file train-00031_problem_info_24.json
python convert_train_code.py --input_file train-00031_problem_info_25.json
python convert_train_code.py --input_file train-00031_problem_info_26.json
python convert_train_code.py --input_file train-00031_problem_info_28.json
python convert_train_code.py --input_file train-00031_problem_info_29.json
python convert_train_code.py --input_file train-00032_problem_info_0.json
python convert_train_code.py --input_file train-00032_problem_info_1.json
python convert_train_code.py --input_file train-00032_problem_info_2.json
python convert_train_code.py --input_file train-00032_problem_info_8.json
python convert_train_code.py --input_file train-00032_problem_info_14.json
python convert_train_code.py --input_file train-00032_problem_info_16.json
python convert_train_code.py --input_file train-00032_problem_info_18.json
python convert_train_code.py --input_file train-00032_problem_info_20.json
python convert_train_code.py --input_file train-00032_problem_info_24.json
python convert_train_code.py --input_file train-00032_problem_info_25.json
python convert_train_code.py --input_file train-00033_problem_info_1.json
python convert_train_code.py --input_file train-00033_problem_info_8.json
python convert_train_code.py --input_file train-00033_problem_info_13.json
python convert_train_code.py --input_file train-00033_problem_info_17.json
python convert_train_code.py --input_file train-00033_problem_info_18.json
python convert_train_code.py --input_file train-00033_problem_info_22.json
python convert_train_code.py --input_file train-00033_problem_info_23.json
python convert_train_code.py --input_file train-00034_problem_info_1.json
python convert_train_code.py --input_file train-00034_problem_info_6.json
python convert_train_code.py --input_file train-00034_problem_info_7.json
python convert_train_code.py --input_file train-00034_problem_info_8.json
python convert_train_code.py --input_file train-00034_problem_info_13.json
python convert_train_code.py --input_file train-00034_problem_info_19.json
python convert_train_code.py --input_file train-00034_problem_info_21.json
python convert_train_code.py --input_file train-00034_problem_info_22.json
python convert_train_code.py --input_file train-00034_problem_info_23.json
python convert_train_code.py --input_file train-00034_problem_info_28.json
python convert_train_code.py --input_file train-00034_problem_info_29.json
python convert_train_code.py --input_file train-00035_problem_info_2.json
python convert_train_code.py --input_file train-00035_problem_info_12.json
python convert_train_code.py --input_file train-00035_problem_info_14.json
python convert_train_code.py --input_file train-00035_problem_info_16.json
python convert_train_code.py --input_file train-00035_problem_info_17.json
python convert_train_code.py --input_file train-00035_problem_info_20.json
python convert_train_code.py --input_file train-00035_problem_info_22.json
python convert_train_code.py --input_file train-00036_problem_info_1.json
python convert_train_code.py --input_file train-00036_problem_info_4.json
python convert_train_code.py --input_file train-00036_problem_info_11.json
python convert_train_code.py --input_file train-00036_problem_info_15.json
python convert_train_code.py --input_file train-00036_problem_info_18.json
python convert_train_code.py --input_file train-00036_problem_info_19.json
python convert_train_code.py --input_file train-00037_problem_info_0.json
python convert_train_code.py --input_file train-00037_problem_info_8.json
python convert_train_code.py --input_file train-00037_problem_info_9.json
python convert_train_code.py --input_file train-00037_problem_info_12.json
python convert_train_code.py --input_file train-00037_problem_info_13.json
python convert_train_code.py --input_file train-00037_problem_info_15.json
python convert_train_code.py --input_file train-00037_problem_info_16.json
python convert_train_code.py --input_file train-00037_problem_info_18.json
python convert_train_code.py --input_file train-00037_problem_info_20.json
python convert_train_code.py --input_file train-00037_problem_info_21.json
python convert_train_code.py --input_file train-00037_problem_info_25.json
python convert_train_code.py --input_file train-00038_problem_info_1.json
python convert_train_code.py --input_file train-00038_problem_info_4.json
python convert_train_code.py --input_file train-00038_problem_info_10.json
python convert_train_code.py --input_file train-00038_problem_info_12.json
python convert_train_code.py --input_file train-00038_problem_info_19.json
python convert_train_code.py --input_file train-00038_problem_info_21.json
python convert_train_code.py --input_file train-00038_problem_info_25.json
python convert_train_code.py --input_file train-00038_problem_info_26.json
python convert_train_code.py --input_file train-00038_problem_info_27.json
python convert_train_code.py --input_file train-00038_problem_info_29.json
python convert_train_code.py --input_file train-00038_problem_info_30.json
python convert_train_code.py --input_file train-00039_problem_info_1.json
python convert_train_code.py --input_file train-00039_problem_info_2.json
python convert_train_code.py --input_file train-00039_problem_info_3.json
python convert_train_code.py --input_file train-00039_problem_info_4.json
python convert_train_code.py --input_file train-00039_problem_info_8.json
python convert_train_code.py --input_file train-00039_problem_info_10.json
python convert_train_code.py --input_file train-00039_problem_info_11.json
python convert_train_code.py --input_file train-00039_problem_info_14.json
python convert_train_code.py --input_file train-00039_problem_info_15.json
python convert_train_code.py --input_file train-00039_problem_info_18.json
python convert_train_code.py --input_file train-00039_problem_info_19.json
python convert_train_code.py --input_file train-00039_problem_info_23.json
python convert_train_code.py --input_file train-00039_problem_info_25.json
python convert_train_code.py --input_file train-00039_problem_info_26.json
python convert_train_code.py --input_file train-00039_problem_info_28.json
python convert_train_code.py --input_file train-00039_problem_info_33.json
python convert_train_code.py --input_file train-00039_problem_info_34.json
python convert_train_code.py --input_file train-00039_problem_info_36.json
python convert_train_code.py --input_file train-00039_problem_info_37.json
python convert_train_code.py --input_file train-00040_problem_info_8.json
python convert_train_code.py --input_file train-00040_problem_info_9.json
python convert_train_code.py --input_file train-00040_problem_info_19.json
python convert_train_code.py --input_file train-00040_problem_info_20.json
python convert_train_code.py --input_file train-00040_problem_info_23.json
python convert_train_code.py --input_file train-00041_problem_info_7.json
python convert_train_code.py --input_file train-00041_problem_info_16.json
python convert_train_code.py --input_file train-00041_problem_info_20.json
python convert_train_code.py --input_file train-00041_problem_info_24.json
python convert_train_code.py --input_file train-00041_problem_info_26.json
python convert_train_code.py --input_file train-00042_problem_info_0.json
python convert_train_code.py --input_file train-00042_problem_info_2.json
python convert_train_code.py --input_file train-00042_problem_info_6.json
python convert_train_code.py --input_file train-00042_problem_info_10.json
python convert_train_code.py --input_file train-00042_problem_info_12.json
python convert_train_code.py --input_file train-00042_problem_info_14.json
python convert_train_code.py --input_file train-00042_problem_info_18.json
python convert_train_code.py --input_file train-00042_problem_info_21.json
python convert_train_code.py --input_file train-00043_problem_info_3.json
python convert_train_code.py --input_file train-00043_problem_info_5.json
python convert_train_code.py --input_file train-00043_problem_info_7.json
python convert_train_code.py --input_file train-00043_problem_info_9.json
python convert_train_code.py --input_file train-00043_problem_info_13.json
python convert_train_code.py --input_file train-00043_problem_info_16.json
python convert_train_code.py --input_file train-00043_problem_info_18.json
python convert_train_code.py --input_file train-00043_problem_info_19.json
python convert_train_code.py --input_file train-00043_problem_info_22.json
python convert_train_code.py --input_file train-00043_problem_info_23.json
python convert_train_code.py --input_file train-00044_problem_info_7.json
python convert_train_code.py --input_file train-00044_problem_info_8.json
python convert_train_code.py --input_file train-00044_problem_info_11.json
python convert_train_code.py --input_file train-00044_problem_info_12.json
python convert_train_code.py --input_file train-00044_problem_info_14.json
python convert_train_code.py --input_file train-00044_problem_info_15.json
python convert_train_code.py --input_file train-00044_problem_info_18.json
python convert_train_code.py --input_file train-00044_problem_info_22.json
python convert_train_code.py --input_file train-00044_problem_info_24.json
python convert_train_code.py --input_file train-00044_problem_info_26.json
python convert_train_code.py --input_file train-00044_problem_info_27.json
python convert_train_code.py --input_file train-00044_problem_info_29.json
python convert_train_code.py --input_file train-00045_problem_info_1.json
python convert_train_code.py --input_file train-00045_problem_info_4.json
python convert_train_code.py --input_file train-00045_problem_info_10.json
python convert_train_code.py --input_file train-00045_problem_info_11.json
python convert_train_code.py --input_file train-00045_problem_info_18.json
python convert_train_code.py --input_file train-00045_problem_info_19.json
python convert_train_code.py --input_file train-00045_problem_info_21.json
python convert_train_code.py --input_file train-00045_problem_info_22.json
python convert_train_code.py --input_file train-00045_problem_info_25.json
python convert_train_code.py --input_file train-00045_problem_info_27.json
python convert_train_code.py --input_file train-00045_problem_info_28.json
python convert_train_code.py --input_file train-00045_problem_info_32.json
python convert_train_code.py --input_file train-00046_problem_info_2.json
python convert_train_code.py --input_file train-00046_problem_info_3.json
python convert_train_code.py --input_file train-00046_problem_info_16.json
python convert_train_code.py --input_file train-00046_problem_info_20.json
python convert_train_code.py --input_file train-00047_problem_info_1.json
python convert_train_code.py --input_file train-00047_problem_info_3.json
python convert_train_code.py --input_file train-00047_problem_info_9.json
python convert_train_code.py --input_file train-00047_problem_info_10.json
python convert_train_code.py --input_file train-00047_problem_info_11.json
python convert_train_code.py --input_file train-00047_problem_info_12.json
python convert_train_code.py --input_file train-00047_problem_info_15.json
python convert_train_code.py --input_file train-00047_problem_info_17.json
python convert_train_code.py --input_file train-00047_problem_info_19.json
python convert_train_code.py --input_file train-00047_problem_info_21.json
python convert_train_code.py --input_file train-00047_problem_info_22.json
python convert_train_code.py --input_file train-00047_problem_info_27.json
python convert_train_code.py --input_file train-00047_problem_info_29.json
python convert_train_code.py --input_file train-00048_problem_info_5.json
python convert_train_code.py --input_file train-00048_problem_info_11.json
python convert_train_code.py --input_file train-00048_problem_info_14.json
python convert_train_code.py --input_file train-00048_problem_info_17.json
python convert_train_code.py --input_file train-00048_problem_info_23.json
python convert_train_code.py --input_file train-00049_problem_info_3.json
python convert_train_code.py --input_file train-00049_problem_info_4.json
python convert_train_code.py --input_file train-00049_problem_info_7.json
python convert_train_code.py --input_file train-00049_problem_info_13.json
python convert_train_code.py --input_file train-00049_problem_info_14.json
python convert_train_code.py --input_file train-00049_problem_info_16.json
python convert_train_code.py --input_file train-00049_problem_info_17.json
python convert_train_code.py --input_file train-00049_problem_info_18.json
python convert_train_code.py --input_file train-00049_problem_info_19.json
python convert_train_code.py --input_file train-00049_problem_info_25.json
python convert_train_code.py --input_file train-00049_problem_info_26.json
python convert_train_code.py --input_file train-00049_problem_info_27.json
python convert_train_code.py --input_file train-00049_problem_info_30.json
python convert_train_code.py --input_file train-00049_problem_info_31.json
python convert_train_code.py --input_file train-00050_problem_info_5.json
python convert_train_code.py --input_file train-00050_problem_info_12.json
python convert_train_code.py --input_file train-00050_problem_info_16.json
python convert_train_code.py --input_file train-00050_problem_info_17.json
python convert_train_code.py --input_file train-00050_problem_info_22.json
python convert_train_code.py --input_file train-00051_problem_info_5.json
python convert_train_code.py --input_file train-00051_problem_info_9.json
python convert_train_code.py --input_file train-00051_problem_info_13.json
python convert_train_code.py --input_file train-00051_problem_info_15.json
python convert_train_code.py --input_file train-00051_problem_info_17.json
python convert_train_code.py --input_file train-00051_problem_info_18.json
python convert_train_code.py --input_file train-00051_problem_info_20.json
python convert_train_code.py --input_file train-00051_problem_info_21.json
python convert_train_code.py --input_file train-00052_problem_info_0.json
python convert_train_code.py --input_file train-00052_problem_info_9.json
python convert_train_code.py --input_file train-00052_problem_info_12.json
python convert_train_code.py --input_file train-00052_problem_info_13.json
python convert_train_code.py --input_file train-00052_problem_info_20.json
python convert_train_code.py --input_file train-00052_problem_info_21.json
python convert_train_code.py --input_file train-00053_problem_info_1.json
python convert_train_code.py --input_file train-00053_problem_info_2.json
python convert_train_code.py --input_file train-00053_problem_info_4.json
python convert_train_code.py --input_file train-00053_problem_info_6.json
python convert_train_code.py --input_file train-00053_problem_info_12.json
python convert_train_code.py --input_file train-00053_problem_info_15.json
python convert_train_code.py --input_file train-00053_problem_info_17.json
python convert_train_code.py --input_file train-00053_problem_info_18.json
python convert_train_code.py --input_file train-00053_problem_info_19.json
python convert_train_code.py --input_file train-00053_problem_info_21.json
python convert_train_code.py --input_file train-00053_problem_info_24.json
python convert_train_code.py --input_file train-00054_problem_info_1.json
python convert_train_code.py --input_file train-00054_problem_info_3.json
python convert_train_code.py --input_file train-00054_problem_info_4.json
python convert_train_code.py --input_file train-00054_problem_info_5.json
python convert_train_code.py --input_file train-00054_problem_info_7.json
python convert_train_code.py --input_file train-00054_problem_info_11.json
python convert_train_code.py --input_file train-00054_problem_info_15.json
python convert_train_code.py --input_file train-00054_problem_info_17.json
python convert_train_code.py --input_file train-00054_problem_info_18.json
python convert_train_code.py --input_file train-00054_problem_info_20.json
python convert_train_code.py --input_file train-00054_problem_info_25.json
python convert_train_code.py --input_file train-00054_problem_info_27.json
python convert_train_code.py --input_file train-00054_problem_info_28.json
python convert_train_code.py --input_file train-00054_problem_info_29.json
python convert_train_code.py --input_file train-00055_problem_info_13.json
python convert_train_code.py --input_file train-00055_problem_info_17.json
python convert_train_code.py --input_file train-00055_problem_info_19.json
python convert_train_code.py --input_file train-00055_problem_info_25.json
python convert_train_code.py --input_file train-00055_problem_info_26.json
python convert_train_code.py --input_file train-00055_problem_info_30.json
python convert_train_code.py --input_file train-00056_problem_info_1.json
python convert_train_code.py --input_file train-00056_problem_info_6.json
python convert_train_code.py --input_file train-00056_problem_info_8.json
python convert_train_code.py --input_file train-00056_problem_info_9.json
python convert_train_code.py --input_file train-00056_problem_info_15.json
python convert_train_code.py --input_file train-00056_problem_info_17.json
python convert_train_code.py --input_file train-00056_problem_info_19.json
python convert_train_code.py --input_file train-00056_problem_info_21.json
python convert_train_code.py --input_file train-00057_problem_info_1.json
python convert_train_code.py --input_file train-00057_problem_info_3.json
python convert_train_code.py --input_file train-00057_problem_info_10.json
python convert_train_code.py --input_file train-00057_problem_info_12.json
python convert_train_code.py --input_file train-00057_problem_info_15.json
python convert_train_code.py --input_file train-00057_problem_info_17.json
python convert_train_code.py --input_file train-00058_problem_info_0.json
python convert_train_code.py --input_file train-00058_problem_info_5.json
python convert_train_code.py --input_file train-00058_problem_info_8.json
python convert_train_code.py --input_file train-00058_problem_info_11.json
python convert_train_code.py --input_file train-00058_problem_info_12.json
python convert_train_code.py --input_file train-00058_problem_info_13.json
python convert_train_code.py --input_file train-00058_problem_info_15.json
python convert_train_code.py --input_file train-00059_problem_info_0.json
python convert_train_code.py --input_file train-00059_problem_info_2.json
python convert_train_code.py --input_file train-00059_problem_info_4.json
python convert_train_code.py --input_file train-00059_problem_info_7.json
python convert_train_code.py --input_file train-00059_problem_info_10.json
python convert_train_code.py --input_file train-00059_problem_info_17.json
python convert_train_code.py --input_file train-00059_problem_info_18.json
python convert_train_code.py --input_file train-00059_problem_info_19.json
python convert_train_code.py --input_file train-00059_problem_info_20.json
python convert_train_code.py --input_file train-00059_problem_info_21.json
python convert_train_code.py --input_file train-00059_problem_info_23.json
python convert_train_code.py --input_file train-00059_problem_info_25.json
python convert_train_code.py --input_file train-00059_problem_info_26.json
python convert_train_code.py --input_file train-00059_problem_info_30.json
python convert_train_code.py --input_file train-00059_problem_info_33.json
python convert_train_code.py --input_file train-00059_problem_info_34.json
python convert_train_code.py --input_file train-00060_problem_info_2.json
python convert_train_code.py --input_file train-00060_problem_info_3.json
python convert_train_code.py --input_file train-00060_problem_info_12.json
python convert_train_code.py --input_file train-00060_problem_info_14.json
python convert_train_code.py --input_file train-00060_problem_info_17.json
python convert_train_code.py --input_file train-00060_problem_info_19.json
python convert_train_code.py --input_file train-00060_problem_info_25.json
python convert_train_code.py --input_file train-00060_problem_info_29.json
python convert_train_code.py --input_file train-00061_problem_info_1.json
python convert_train_code.py --input_file train-00061_problem_info_17.json
python convert_train_code.py --input_file train-00061_problem_info_19.json
python convert_train_code.py --input_file train-00061_problem_info_27.json
python convert_train_code.py --input_file train-00062_problem_info_0.json
python convert_train_code.py --input_file train-00062_problem_info_10.json
python convert_train_code.py --input_file train-00062_problem_info_15.json
python convert_train_code.py --input_file train-00062_problem_info_16.json
python convert_train_code.py --input_file train-00062_problem_info_18.json
python convert_train_code.py --input_file train-00062_problem_info_20.json
python convert_train_code.py --input_file train-00062_problem_info_22.json
python convert_train_code.py --input_file train-00062_problem_info_23.json
python convert_train_code.py --input_file train-00063_problem_info_1.json
python convert_train_code.py --input_file train-00063_problem_info_2.json
python convert_train_code.py --input_file train-00063_problem_info_8.json
python convert_train_code.py --input_file train-00063_problem_info_9.json
python convert_train_code.py --input_file train-00063_problem_info_10.json
python convert_train_code.py --input_file train-00063_problem_info_14.json
python convert_train_code.py --input_file train-00063_problem_info_15.json
python convert_train_code.py --input_file train-00063_problem_info_17.json
python convert_train_code.py --input_file train-00063_problem_info_19.json
python convert_train_code.py --input_file train-00063_problem_info_20.json
python convert_train_code.py --input_file train-00063_problem_info_21.json
python convert_train_code.py --input_file train-00064_problem_info_0.json
python convert_train_code.py --input_file train-00064_problem_info_2.json
python convert_train_code.py --input_file train-00064_problem_info_4.json
python convert_train_code.py --input_file train-00064_problem_info_6.json
python convert_train_code.py --input_file train-00064_problem_info_8.json
python convert_train_code.py --input_file train-00064_problem_info_11.json
python convert_train_code.py --input_file train-00064_problem_info_12.json
python convert_train_code.py --input_file train-00064_problem_info_16.json
python convert_train_code.py --input_file train-00064_problem_info_17.json
python convert_train_code.py --input_file train-00064_problem_info_19.json
python convert_train_code.py --input_file train-00064_problem_info_26.json
python convert_train_code.py --input_file train-00065_problem_info_0.json
python convert_train_code.py --input_file train-00065_problem_info_2.json
python convert_train_code.py --input_file train-00065_problem_info_4.json
python convert_train_code.py --input_file train-00065_problem_info_9.json
python convert_train_code.py --input_file train-00065_problem_info_12.json
python convert_train_code.py --input_file train-00065_problem_info_17.json
python convert_train_code.py --input_file train-00065_problem_info_20.json
python convert_train_code.py --input_file train-00065_problem_info_21.json
python convert_train_code.py --input_file train-00065_problem_info_24.json
python convert_train_code.py --input_file train-00065_problem_info_27.json
python convert_train_code.py --input_file train-00066_problem_info_6.json
python convert_train_code.py --input_file train-00066_problem_info_7.json
python convert_train_code.py --input_file train-00066_problem_info_8.json
python convert_train_code.py --input_file train-00066_problem_info_11.json
python convert_train_code.py --input_file train-00066_problem_info_13.json
python convert_train_code.py --input_file train-00066_problem_info_20.json
python convert_train_code.py --input_file train-00066_problem_info_21.json
python convert_train_code.py --input_file train-00066_problem_info_24.json
python convert_train_code.py --input_file train-00066_problem_info_26.json
python convert_train_code.py --input_file train-00067_problem_info_18.json
python convert_train_code.py --input_file train-00067_problem_info_19.json
python convert_train_code.py --input_file train-00067_problem_info_22.json
python convert_train_code.py --input_file train-00067_problem_info_23.json
python convert_train_code.py --input_file train-00067_problem_info_25.json
python convert_train_code.py --input_file train-00067_problem_info_26.json
python convert_train_code.py --input_file train-00067_problem_info_27.json
python convert_train_code.py --input_file train-00068_problem_info_5.json
python convert_train_code.py --input_file train-00068_problem_info_11.json
python convert_train_code.py --input_file train-00068_problem_info_12.json
python convert_train_code.py --input_file train-00068_problem_info_14.json
python convert_train_code.py --input_file train-00068_problem_info_17.json
python convert_train_code.py --input_file train-00068_problem_info_18.json
python convert_train_code.py --input_file train-00069_problem_info_1.json
python convert_train_code.py --input_file train-00069_problem_info_2.json
python convert_train_code.py --input_file train-00069_problem_info_4.json
python convert_train_code.py --input_file train-00069_problem_info_6.json
python convert_train_code.py --input_file train-00069_problem_info_9.json
python convert_train_code.py --input_file train-00069_problem_info_10.json
python convert_train_code.py --input_file train-00069_problem_info_14.json
python convert_train_code.py --input_file train-00069_problem_info_15.json
python convert_train_code.py --input_file train-00069_problem_info_18.json
python convert_train_code.py --input_file train-00069_problem_info_25.json
python convert_train_code.py --input_file train-00069_problem_info_26.json
python convert_train_code.py --input_file train-00069_problem_info_29.json
python convert_train_code.py --input_file train-00070_problem_info_3.json
python convert_train_code.py --input_file train-00070_problem_info_5.json
python convert_train_code.py --input_file train-00070_problem_info_7.json
python convert_train_code.py --input_file train-00070_problem_info_8.json
python convert_train_code.py --input_file train-00070_problem_info_12.json
python convert_train_code.py --input_file train-00070_problem_info_13.json
python convert_train_code.py --input_file train-00070_problem_info_17.json
python convert_train_code.py --input_file train-00071_problem_info_0.json
python convert_train_code.py --input_file train-00071_problem_info_1.json
python convert_train_code.py --input_file train-00071_problem_info_4.json
python convert_train_code.py --input_file train-00071_problem_info_5.json
python convert_train_code.py --input_file train-00071_problem_info_6.json
python convert_train_code.py --input_file train-00071_problem_info_7.json
python convert_train_code.py --input_file train-00071_problem_info_11.json
python convert_train_code.py --input_file train-00071_problem_info_17.json
python convert_train_code.py --input_file train-00071_problem_info_22.json
python convert_train_code.py --input_file train-00071_problem_info_23.json
python convert_train_code.py --input_file train-00071_problem_info_25.json
python convert_train_code.py --input_file train-00072_problem_info_2.json
python convert_train_code.py --input_file train-00072_problem_info_3.json
python convert_train_code.py --input_file train-00072_problem_info_4.json
python convert_train_code.py --input_file train-00072_problem_info_8.json
python convert_train_code.py --input_file train-00072_problem_info_15.json
python convert_train_code.py --input_file train-00072_problem_info_18.json
python convert_train_code.py --input_file train-00072_problem_info_19.json
python convert_train_code.py --input_file train-00072_problem_info_21.json
python convert_train_code.py --input_file train-00072_problem_info_24.json
python convert_train_code.py --input_file train-00072_problem_info_26.json
python convert_train_code.py --input_file train-00073_problem_info_14.json
python convert_train_code.py --input_file train-00073_problem_info_15.json
python convert_train_code.py --input_file train-00073_problem_info_17.json
python convert_train_code.py --input_file train-00073_problem_info_18.json
python convert_train_code.py --input_file train-00073_problem_info_19.json
python convert_train_code.py --input_file train-00073_problem_info_22.json
python convert_train_code.py --input_file train-00074_problem_info_9.json
python convert_train_code.py --input_file train-00074_problem_info_12.json
python convert_train_code.py --input_file train-00074_problem_info_13.json
python convert_train_code.py --input_file train-00074_problem_info_14.json
python convert_train_code.py --input_file train-00074_problem_info_15.json
python convert_train_code.py --input_file train-00074_problem_info_16.json
python convert_train_code.py --input_file train-00074_problem_info_21.json
python convert_train_code.py --input_file train-00074_problem_info_23.json
python convert_train_code.py --input_file train-00074_problem_info_24.json
python convert_train_code.py --input_file train-00075_problem_info_0.json
python convert_train_code.py --input_file train-00075_problem_info_1.json
python convert_train_code.py --input_file train-00075_problem_info_8.json
python convert_train_code.py --input_file train-00075_problem_info_10.json
python convert_train_code.py --input_file train-00075_problem_info_14.json
python convert_train_code.py --input_file train-00075_problem_info_18.json
python convert_train_code.py --input_file train-00075_problem_info_22.json
python convert_train_code.py --input_file train-00075_problem_info_23.json
python convert_train_code.py --input_file train-00075_problem_info_24.json
python convert_train_code.py --input_file train-00075_problem_info_26.json
python convert_train_code.py --input_file train-00075_problem_info_28.json
python convert_train_code.py --input_file train-00076_problem_info_2.json
python convert_train_code.py --input_file train-00076_problem_info_3.json
python convert_train_code.py --input_file train-00076_problem_info_7.json
python convert_train_code.py --input_file train-00076_problem_info_12.json
python convert_train_code.py --input_file train-00076_problem_info_13.json
python convert_train_code.py --input_file train-00076_problem_info_18.json
python convert_train_code.py --input_file train-00076_problem_info_20.json
python convert_train_code.py --input_file train-00077_problem_info_0.json
python convert_train_code.py --input_file train-00077_problem_info_2.json
python convert_train_code.py --input_file train-00077_problem_info_4.json
python convert_train_code.py --input_file train-00077_problem_info_8.json
python convert_train_code.py --input_file train-00077_problem_info_10.json
python convert_train_code.py --input_file train-00077_problem_info_16.json
python convert_train_code.py --input_file train-00077_problem_info_17.json
python convert_train_code.py --input_file train-00077_problem_info_21.json
python convert_train_code.py --input_file train-00077_problem_info_22.json
python convert_train_code.py --input_file train-00077_problem_info_25.json
python convert_train_code.py --input_file train-00077_problem_info_28.json
python convert_train_code.py --input_file train-00077_problem_info_29.json
python convert_train_code.py --input_file train-00078_problem_info_7.json
python convert_train_code.py --input_file train-00078_problem_info_14.json
python convert_train_code.py --input_file train-00078_problem_info_16.json
python convert_train_code.py --input_file train-00078_problem_info_20.json
python convert_train_code.py --input_file train-00078_problem_info_21.json
python convert_train_code.py --input_file train-00078_problem_info_24.json
python convert_train_code.py --input_file train-00078_problem_info_25.json
python convert_train_code.py --input_file train-00079_problem_info_1.json
python convert_train_code.py --input_file train-00079_problem_info_4.json
python convert_train_code.py --input_file train-00079_problem_info_6.json
python convert_train_code.py --input_file train-00079_problem_info_10.json
python convert_train_code.py --input_file train-00079_problem_info_11.json
python convert_train_code.py --input_file train-00079_problem_info_13.json
python convert_train_code.py --input_file train-00079_problem_info_14.json
python convert_train_code.py --input_file train-00079_problem_info_16.json
python convert_train_code.py --input_file train-00079_problem_info_17.json
python convert_train_code.py --input_file train-00079_problem_info_18.json
python convert_train_code.py --input_file train-00079_problem_info_19.json
python convert_train_code.py --input_file train-00079_problem_info_21.json
python convert_train_code.py --input_file train-00079_problem_info_23.json
python convert_train_code.py --input_file train-00079_problem_info_26.json
python convert_train_code.py --input_file train-00079_problem_info_29.json
python convert_train_code.py --input_file train-00080_problem_info_2.json
python convert_train_code.py --input_file train-00080_problem_info_4.json
python convert_train_code.py --input_file train-00080_problem_info_10.json
python convert_train_code.py --input_file train-00080_problem_info_14.json
python convert_train_code.py --input_file train-00080_problem_info_19.json
python convert_train_code.py --input_file train-00080_problem_info_21.json
python convert_train_code.py --input_file train-00081_problem_info_2.json
python convert_train_code.py --input_file train-00081_problem_info_5.json
python convert_train_code.py --input_file train-00081_problem_info_6.json
python convert_train_code.py --input_file train-00081_problem_info_17.json
python convert_train_code.py --input_file train-00081_problem_info_18.json
python convert_train_code.py --input_file train-00081_problem_info_21.json
python convert_train_code.py --input_file train-00081_problem_info_25.json
python convert_train_code.py --input_file train-00082_problem_info_1.json
python convert_train_code.py --input_file train-00082_problem_info_2.json
python convert_train_code.py --input_file train-00082_problem_info_10.json
python convert_train_code.py --input_file train-00082_problem_info_15.json
python convert_train_code.py --input_file train-00082_problem_info_16.json
python convert_train_code.py --input_file train-00082_problem_info_18.json
python convert_train_code.py --input_file train-00082_problem_info_20.json
python convert_train_code.py --input_file train-00082_problem_info_21.json
python convert_train_code.py --input_file train-00082_problem_info_25.json
python convert_train_code.py --input_file train-00082_problem_info_26.json
python convert_train_code.py --input_file train-00082_problem_info_27.json
python convert_train_code.py --input_file train-00082_problem_info_28.json
python convert_train_code.py --input_file train-00082_problem_info_29.json
python convert_train_code.py --input_file train-00083_problem_info_0.json
python convert_train_code.py --input_file train-00083_problem_info_1.json
python convert_train_code.py --input_file train-00083_problem_info_9.json
python convert_train_code.py --input_file train-00083_problem_info_10.json
python convert_train_code.py --input_file train-00083_problem_info_12.json
python convert_train_code.py --input_file train-00083_problem_info_15.json
python convert_train_code.py --input_file train-00083_problem_info_17.json
python convert_train_code.py --input_file train-00083_problem_info_19.json
python convert_train_code.py --input_file train-00083_problem_info_22.json
python convert_train_code.py --input_file train-00083_problem_info_27.json
python convert_train_code.py --input_file train-00084_problem_info_4.json
python convert_train_code.py --input_file train-00084_problem_info_13.json
python convert_train_code.py --input_file train-00084_problem_info_15.json
python convert_train_code.py --input_file train-00084_problem_info_16.json
python convert_train_code.py --input_file train-00084_problem_info_20.json
python convert_train_code.py --input_file train-00084_problem_info_25.json
python convert_train_code.py --input_file train-00084_problem_info_26.json
python convert_train_code.py --input_file train-00084_problem_info_34.json
python convert_train_code.py --input_file train-00084_problem_info_35.json
python convert_train_code.py --input_file train-00085_problem_info_10.json
python convert_train_code.py --input_file train-00085_problem_info_12.json
python convert_train_code.py --input_file train-00085_problem_info_13.json
python convert_train_code.py --input_file train-00085_problem_info_18.json
python convert_train_code.py --input_file train-00085_problem_info_19.json
python convert_train_code.py --input_file train-00085_problem_info_20.json
python convert_train_code.py --input_file train-00086_problem_info_4.json
python convert_train_code.py --input_file train-00086_problem_info_7.json
python convert_train_code.py --input_file train-00086_problem_info_10.json
python convert_train_code.py --input_file train-00086_problem_info_17.json
python convert_train_code.py --input_file train-00086_problem_info_18.json
python convert_train_code.py --input_file train-00086_problem_info_20.json
python convert_train_code.py --input_file train-00086_problem_info_21.json
python convert_train_code.py --input_file train-00087_problem_info_2.json
python convert_train_code.py --input_file train-00087_problem_info_3.json
python convert_train_code.py --input_file train-00087_problem_info_6.json
python convert_train_code.py --input_file train-00087_problem_info_14.json
python convert_train_code.py --input_file train-00087_problem_info_15.json
python convert_train_code.py --input_file train-00087_problem_info_18.json
python convert_train_code.py --input_file train-00087_problem_info_19.json
python convert_train_code.py --input_file train-00087_problem_info_20.json
python convert_train_code.py --input_file train-00087_problem_info_26.json
python convert_train_code.py --input_file train-00087_problem_info_28.json
python convert_train_code.py --input_file train-00087_problem_info_29.json
python convert_train_code.py --input_file train-00088_problem_info_0.json
python convert_train_code.py --input_file train-00088_problem_info_1.json
python convert_train_code.py --input_file train-00088_problem_info_5.json
python convert_train_code.py --input_file train-00088_problem_info_14.json
python convert_train_code.py --input_file train-00088_problem_info_15.json
python convert_train_code.py --input_file train-00088_problem_info_17.json
python convert_train_code.py --input_file train-00088_problem_info_20.json
python convert_train_code.py --input_file train-00089_problem_info_0.json
python convert_train_code.py --input_file train-00089_problem_info_6.json
python convert_train_code.py --input_file train-00089_problem_info_7.json
python convert_train_code.py --input_file train-00089_problem_info_8.json
python convert_train_code.py --input_file train-00089_problem_info_10.json
python convert_train_code.py --input_file train-00089_problem_info_12.json
python convert_train_code.py --input_file train-00089_problem_info_13.json
python convert_train_code.py --input_file train-00089_problem_info_14.json
python convert_train_code.py --input_file train-00089_problem_info_16.json
python convert_train_code.py --input_file train-00089_problem_info_20.json
python convert_train_code.py --input_file train-00089_problem_info_21.json
python convert_train_code.py --input_file train-00089_problem_info_22.json
python convert_train_code.py --input_file train-00089_problem_info_25.json
python convert_train_code.py --input_file train-00089_problem_info_26.json
python convert_train_code.py --input_file train-00090_problem_info_0.json
python convert_train_code.py --input_file train-00090_problem_info_1.json
python convert_train_code.py --input_file train-00090_problem_info_3.json
python convert_train_code.py --input_file train-00090_problem_info_6.json
python convert_train_code.py --input_file train-00090_problem_info_9.json
python convert_train_code.py --input_file train-00090_problem_info_13.json
python convert_train_code.py --input_file train-00090_problem_info_14.json
python convert_train_code.py --input_file train-00090_problem_info_20.json
python convert_train_code.py --input_file train-00090_problem_info_21.json
python convert_train_code.py --input_file train-00090_problem_info_25.json
python convert_train_code.py --input_file train-00090_problem_info_29.json
python convert_train_code.py --input_file train-00091_problem_info_12.json
python convert_train_code.py --input_file train-00091_problem_info_14.json
python convert_train_code.py --input_file train-00091_problem_info_15.json
python convert_train_code.py --input_file train-00091_problem_info_18.json
python convert_train_code.py --input_file train-00091_problem_info_19.json
python convert_train_code.py --input_file train-00091_problem_info_20.json
python convert_train_code.py --input_file train-00092_problem_info_3.json
python convert_train_code.py --input_file train-00092_problem_info_5.json
python convert_train_code.py --input_file train-00092_problem_info_10.json
python convert_train_code.py --input_file train-00092_problem_info_15.json
python convert_train_code.py --input_file train-00092_problem_info_16.json
python convert_train_code.py --input_file train-00092_problem_info_18.json
python convert_train_code.py --input_file train-00092_problem_info_19.json
python convert_train_code.py --input_file train-00092_problem_info_23.json
python convert_train_code.py --input_file train-00092_problem_info_25.json
python convert_train_code.py --input_file train-00092_problem_info_26.json
python convert_train_code.py --input_file train-00092_problem_info_27.json
python convert_train_code.py --input_file train-00092_problem_info_28.json
python convert_train_code.py --input_file train-00093_problem_info_1.json
python convert_train_code.py --input_file train-00093_problem_info_7.json
python convert_train_code.py --input_file train-00093_problem_info_17.json
python convert_train_code.py --input_file train-00093_problem_info_19.json
python convert_train_code.py --input_file train-00093_problem_info_20.json
python convert_train_code.py --input_file train-00093_problem_info_22.json
python convert_train_code.py --input_file train-00093_problem_info_27.json
python convert_train_code.py --input_file train-00094_problem_info_3.json
python convert_train_code.py --input_file train-00094_problem_info_8.json
python convert_train_code.py --input_file train-00094_problem_info_9.json
python convert_train_code.py --input_file train-00094_problem_info_12.json
python convert_train_code.py --input_file train-00094_problem_info_13.json
python convert_train_code.py --input_file train-00094_problem_info_14.json
python convert_train_code.py --input_file train-00094_problem_info_16.json
python convert_train_code.py --input_file train-00094_problem_info_20.json
python convert_train_code.py --input_file train-00095_problem_info_0.json
python convert_train_code.py --input_file train-00095_problem_info_1.json
python convert_train_code.py --input_file train-00095_problem_info_3.json
python convert_train_code.py --input_file train-00095_problem_info_6.json
python convert_train_code.py --input_file train-00095_problem_info_7.json
python convert_train_code.py --input_file train-00095_problem_info_9.json
python convert_train_code.py --input_file train-00095_problem_info_12.json
python convert_train_code.py --input_file train-00095_problem_info_18.json
python convert_train_code.py --input_file train-00095_problem_info_20.json
python convert_train_code.py --input_file train-00095_problem_info_23.json
python convert_train_code.py --input_file train-00095_problem_info_24.json
python convert_train_code.py --input_file train-00096_problem_info_2.json
python convert_train_code.py --input_file train-00096_problem_info_6.json
python convert_train_code.py --input_file train-00096_problem_info_7.json
python convert_train_code.py --input_file train-00096_problem_info_14.json
python convert_train_code.py --input_file train-00096_problem_info_16.json
python convert_train_code.py --input_file train-00096_problem_info_18.json
python convert_train_code.py --input_file train-00096_problem_info_19.json
python convert_train_code.py --input_file train-00096_problem_info_21.json
python convert_train_code.py --input_file train-00096_problem_info_22.json
python convert_train_code.py --input_file train-00096_problem_info_23.json
python convert_train_code.py --input_file train-00096_problem_info_24.json
python convert_train_code.py --input_file train-00097_problem_info_0.json
python convert_train_code.py --input_file train-00097_problem_info_10.json
python convert_train_code.py --input_file train-00097_problem_info_13.json
python convert_train_code.py --input_file train-00097_problem_info_14.json
python convert_train_code.py --input_file train-00097_problem_info_15.json
python convert_train_code.py --input_file train-00097_problem_info_16.json
python convert_train_code.py --input_file train-00097_problem_info_17.json
python convert_train_code.py --input_file train-00097_problem_info_19.json
python convert_train_code.py --input_file train-00097_problem_info_20.json
python convert_train_code.py --input_file train-00097_problem_info_28.json
python convert_train_code.py --input_file train-00098_problem_info_3.json
python convert_train_code.py --input_file train-00098_problem_info_7.json
python convert_train_code.py --input_file train-00098_problem_info_11.json
python convert_train_code.py --input_file train-00098_problem_info_16.json
python convert_train_code.py --input_file train-00098_problem_info_20.json
python convert_train_code.py --input_file train-00098_problem_info_24.json
python convert_train_code.py --input_file train-00098_problem_info_26.json
python convert_train_code.py --input_file train-00099_problem_info_3.json
python convert_train_code.py --input_file train-00099_problem_info_5.json
python convert_train_code.py --input_file train-00099_problem_info_6.json
python convert_train_code.py --input_file train-00099_problem_info_7.json
python convert_train_code.py --input_file train-00099_problem_info_12.json
python convert_train_code.py --input_file train-00099_problem_info_13.json
python convert_train_code.py --input_file train-00099_problem_info_16.json
python convert_train_code.py --input_file train-00099_problem_info_19.json
python convert_train_code.py --input_file train-00099_problem_info_20.json
python convert_train_code.py --input_file train-00099_problem_info_23.json
python convert_train_code.py --input_file train-00100_problem_info_0.json
python convert_train_code.py --input_file train-00100_problem_info_3.json
python convert_train_code.py --input_file train-00100_problem_info_7.json
python convert_train_code.py --input_file train-00100_problem_info_13.json
python convert_train_code.py --input_file train-00100_problem_info_15.json
python convert_train_code.py --input_file train-00100_problem_info_19.json
python convert_train_code.py --input_file train-00100_problem_info_23.json
python convert_train_code.py --input_file train-00101_problem_info_1.json
python convert_train_code.py --input_file train-00101_problem_info_5.json
python convert_train_code.py --input_file train-00101_problem_info_6.json
python convert_train_code.py --input_file train-00101_problem_info_7.json
python convert_train_code.py --input_file train-00101_problem_info_12.json
python convert_train_code.py --input_file train-00101_problem_info_14.json
python convert_train_code.py --input_file train-00101_problem_info_16.json
python convert_train_code.py --input_file train-00101_problem_info_18.json
python convert_train_code.py --input_file train-00101_problem_info_21.json
python convert_train_code.py --input_file train-00101_problem_info_25.json
python convert_train_code.py --input_file train-00102_problem_info_2.json
python convert_train_code.py --input_file train-00102_problem_info_6.json
python convert_train_code.py --input_file train-00102_problem_info_13.json
python convert_train_code.py --input_file train-00102_problem_info_15.json
python convert_train_code.py --input_file train-00102_problem_info_16.json
python convert_train_code.py --input_file train-00102_problem_info_17.json
python convert_train_code.py --input_file train-00102_problem_info_18.json
python convert_train_code.py --input_file train-00102_problem_info_20.json
python convert_train_code.py --input_file train-00102_problem_info_22.json
python convert_train_code.py --input_file train-00102_problem_info_23.json
python convert_train_code.py --input_file train-00103_problem_info_2.json
python convert_train_code.py --input_file train-00103_problem_info_3.json
python convert_train_code.py --input_file train-00103_problem_info_13.json
python convert_train_code.py --input_file train-00103_problem_info_14.json
python convert_train_code.py --input_file train-00103_problem_info_16.json
python convert_train_code.py --input_file train-00103_problem_info_20.json
python convert_train_code.py --input_file train-00103_problem_info_24.json
python convert_train_code.py --input_file train-00103_problem_info_25.json
python convert_train_code.py --input_file train-00104_problem_info_6.json
python convert_train_code.py --input_file train-00104_problem_info_10.json
python convert_train_code.py --input_file train-00104_problem_info_11.json
python convert_train_code.py --input_file train-00104_problem_info_12.json
python convert_train_code.py --input_file train-00104_problem_info_13.json
python convert_train_code.py --input_file train-00104_problem_info_21.json
python convert_train_code.py --input_file train-00104_problem_info_22.json
python convert_train_code.py --input_file train-00104_problem_info_27.json
python convert_train_code.py --input_file train-00105_problem_info_0.json
python convert_train_code.py --input_file train-00105_problem_info_3.json
python convert_train_code.py --input_file train-00105_problem_info_4.json
python convert_train_code.py --input_file train-00105_problem_info_16.json
python convert_train_code.py --input_file train-00105_problem_info_18.json
python convert_train_code.py --input_file train-00105_problem_info_23.json
python convert_train_code.py --input_file train-00105_problem_info_26.json
python convert_train_code.py --input_file train-00105_problem_info_27.json
python convert_train_code.py --input_file train-00106_problem_info_0.json
python convert_train_code.py --input_file train-00106_problem_info_8.json
python convert_train_code.py --input_file train-00106_problem_info_9.json
python convert_train_code.py --input_file train-00106_problem_info_14.json
python convert_train_code.py --input_file train-00106_problem_info_15.json
python convert_train_code.py --input_file train-00106_problem_info_17.json
python convert_train_code.py --input_file train-00106_problem_info_19.json
python convert_train_code.py --input_file train-00107_problem_info_1.json
python convert_train_code.py --input_file train-00107_problem_info_4.json
python convert_train_code.py --input_file train-00107_problem_info_6.json
python convert_train_code.py --input_file train-00107_problem_info_8.json
python convert_train_code.py --input_file train-00107_problem_info_11.json
python convert_train_code.py --input_file train-00107_problem_info_13.json
python convert_train_code.py --input_file train-00107_problem_info_16.json
python convert_train_code.py --input_file train-00107_problem_info_17.json
python convert_train_code.py --input_file train-00107_problem_info_18.json
python convert_train_code.py --input_file train-00107_problem_info_19.json
python convert_train_code.py --input_file train-00107_problem_info_20.json
python convert_train_code.py --input_file train-00107_problem_info_22.json
python convert_train_code.py --input_file train-00107_problem_info_24.json
python convert_train_code.py --input_file train-00107_problem_info_27.json
python convert_train_code.py --input_file train-00107_problem_info_29.json
python convert_train_code.py --input_file train-00107_problem_info_30.json
python convert_train_code.py --input_file train-00107_problem_info_32.json
python convert_train_code.py --input_file train-00107_problem_info_35.json
python convert_train_code.py --input_file train-00108_problem_info_4.json
python convert_train_code.py --input_file train-00108_problem_info_7.json
python convert_train_code.py --input_file train-00108_problem_info_10.json
python convert_train_code.py --input_file train-00108_problem_info_14.json
python convert_train_code.py --input_file train-00108_problem_info_15.json
python convert_train_code.py --input_file train-00108_problem_info_17.json
python convert_train_code.py --input_file train-00108_problem_info_21.json
python convert_train_code.py --input_file train-00108_problem_info_30.json
python convert_train_code.py --input_file train-00109_problem_info_2.json
python convert_train_code.py --input_file train-00109_problem_info_3.json
python convert_train_code.py --input_file train-00109_problem_info_4.json
python convert_train_code.py --input_file train-00109_problem_info_11.json
python convert_train_code.py --input_file train-00109_problem_info_16.json
python convert_train_code.py --input_file train-00109_problem_info_18.json
python convert_train_code.py --input_file train-00109_problem_info_19.json
python convert_train_code.py --input_file train-00109_problem_info_20.json
python convert_train_code.py --input_file train-00109_problem_info_26.json
python convert_train_code.py --input_file train-00109_problem_info_28.json
python convert_train_code.py --input_file train-00109_problem_info_29.json
python convert_train_code.py --input_file train-00109_problem_info_30.json
python convert_train_code.py --input_file train-00110_problem_info_0.json
python convert_train_code.py --input_file train-00110_problem_info_13.json
python convert_train_code.py --input_file train-00110_problem_info_14.json
python convert_train_code.py --input_file train-00110_problem_info_15.json
python convert_train_code.py --input_file train-00110_problem_info_17.json
python convert_train_code.py --input_file train-00110_problem_info_18.json
python convert_train_code.py --input_file train-00110_problem_info_20.json
python convert_train_code.py --input_file train-00110_problem_info_21.json
python convert_train_code.py --input_file train-00110_problem_info_22.json
python convert_train_code.py --input_file train-00110_problem_info_27.json
python convert_train_code.py --input_file train-00111_problem_info_13.json
python convert_train_code.py --input_file train-00111_problem_info_16.json
python convert_train_code.py --input_file train-00111_problem_info_19.json
python convert_train_code.py --input_file train-00111_problem_info_20.json
python convert_train_code.py --input_file train-00111_problem_info_21.json
python convert_train_code.py --input_file train-00112_problem_info_0.json
python convert_train_code.py --input_file train-00112_problem_info_3.json
python convert_train_code.py --input_file train-00112_problem_info_5.json
python convert_train_code.py --input_file train-00112_problem_info_7.json
python convert_train_code.py --input_file train-00112_problem_info_10.json
python convert_train_code.py --input_file train-00112_problem_info_11.json
python convert_train_code.py --input_file train-00112_problem_info_13.json
python convert_train_code.py --input_file train-00112_problem_info_14.json
python convert_train_code.py --input_file train-00112_problem_info_15.json
python convert_train_code.py --input_file train-00112_problem_info_16.json
python convert_train_code.py --input_file train-00112_problem_info_17.json
python convert_train_code.py --input_file train-00112_problem_info_19.json
python convert_train_code.py --input_file train-00112_problem_info_21.json
python convert_train_code.py --input_file train-00112_problem_info_26.json
python convert_train_code.py --input_file train-00112_problem_info_27.json
python convert_train_code.py --input_file train-00113_problem_info_2.json
python convert_train_code.py --input_file train-00113_problem_info_3.json
python convert_train_code.py --input_file train-00113_problem_info_5.json
python convert_train_code.py --input_file train-00113_problem_info_6.json
python convert_train_code.py --input_file train-00113_problem_info_8.json
python convert_train_code.py --input_file train-00113_problem_info_11.json
python convert_train_code.py --input_file train-00113_problem_info_17.json
python convert_train_code.py --input_file train-00113_problem_info_23.json
python convert_train_code.py --input_file train-00113_problem_info_28.json
python convert_train_code.py --input_file train-00114_problem_info_1.json
python convert_train_code.py --input_file train-00114_problem_info_7.json
python convert_train_code.py --input_file train-00114_problem_info_9.json
python convert_train_code.py --input_file train-00114_problem_info_10.json
python convert_train_code.py --input_file train-00114_problem_info_12.json
python convert_train_code.py --input_file train-00114_problem_info_13.json
python convert_train_code.py --input_file train-00114_problem_info_20.json
python convert_train_code.py --input_file train-00115_problem_info_0.json
python convert_train_code.py --input_file train-00115_problem_info_5.json
python convert_train_code.py --input_file train-00115_problem_info_6.json
python convert_train_code.py --input_file train-00115_problem_info_13.json
python convert_train_code.py --input_file train-00115_problem_info_16.json
python convert_train_code.py --input_file train-00115_problem_info_18.json
python convert_train_code.py --input_file train-00115_problem_info_19.json
python convert_train_code.py --input_file train-00115_problem_info_21.json
python convert_train_code.py --input_file train-00115_problem_info_22.json
python convert_train_code.py --input_file train-00115_problem_info_26.json
python convert_train_code.py --input_file train-00115_problem_info_30.json
python convert_train_code.py --input_file train-00115_problem_info_31.json
python convert_train_code.py --input_file train-00115_problem_info_32.json
python convert_train_code.py --input_file train-00116_problem_info_3.json
python convert_train_code.py --input_file train-00116_problem_info_12.json
python convert_train_code.py --input_file train-00116_problem_info_18.json
python convert_train_code.py --input_file train-00116_problem_info_19.json
python convert_train_code.py --input_file train-00116_problem_info_25.json
python convert_train_code.py --input_file train-00117_problem_info_6.json
python convert_train_code.py --input_file train-00117_problem_info_12.json
python convert_train_code.py --input_file train-00117_problem_info_13.json
python convert_train_code.py --input_file train-00117_problem_info_14.json
python convert_train_code.py --input_file train-00117_problem_info_15.json
python convert_train_code.py --input_file train-00117_problem_info_16.json
python convert_train_code.py --input_file train-00117_problem_info_18.json
python convert_train_code.py --input_file train-00117_problem_info_19.json
python convert_train_code.py --input_file train-00117_problem_info_22.json
python convert_train_code.py --input_file train-00117_problem_info_24.json
python convert_train_code.py --input_file train-00117_problem_info_27.json
python convert_train_code.py --input_file train-00118_problem_info_2.json
python convert_train_code.py --input_file train-00118_problem_info_6.json
python convert_train_code.py --input_file train-00118_problem_info_9.json
python convert_train_code.py --input_file train-00118_problem_info_10.json
python convert_train_code.py --input_file train-00118_problem_info_17.json
python convert_train_code.py --input_file train-00118_problem_info_23.json
python convert_train_code.py --input_file train-00118_problem_info_24.json
python convert_train_code.py --input_file train-00118_problem_info_25.json
python convert_train_code.py --input_file train-00118_problem_info_26.json
python convert_train_code.py --input_file train-00118_problem_info_27.json
python convert_train_code.py --input_file train-00118_problem_info_32.json
python convert_train_code.py --input_file train-00119_problem_info_0.json
python convert_train_code.py --input_file train-00119_problem_info_7.json
python convert_train_code.py --input_file train-00119_problem_info_9.json
python convert_train_code.py --input_file train-00119_problem_info_18.json
python convert_train_code.py --input_file train-00119_problem_info_22.json
python convert_train_code.py --input_file train-00120_problem_info_0.json
python convert_train_code.py --input_file train-00120_problem_info_2.json
python convert_train_code.py --input_file train-00120_problem_info_8.json
python convert_train_code.py --input_file train-00120_problem_info_9.json
python convert_train_code.py --input_file train-00120_problem_info_10.json
python convert_train_code.py --input_file train-00120_problem_info_12.json
python convert_train_code.py --input_file train-00120_problem_info_14.json
python convert_train_code.py --input_file train-00120_problem_info_15.json
python convert_train_code.py --input_file train-00120_problem_info_16.json
python convert_train_code.py --input_file train-00120_problem_info_20.json
python convert_train_code.py --input_file train-00120_problem_info_25.json
python convert_train_code.py --input_file train-00120_problem_info_26.json
python convert_train_code.py --input_file train-00121_problem_info_4.json
python convert_train_code.py --input_file train-00121_problem_info_10.json
python convert_train_code.py --input_file train-00121_problem_info_14.json
python convert_train_code.py --input_file train-00121_problem_info_18.json
python convert_train_code.py --input_file train-00121_problem_info_19.json
python convert_train_code.py --input_file train-00121_problem_info_20.json
python convert_train_code.py --input_file train-00121_problem_info_21.json
python convert_train_code.py --input_file train-00121_problem_info_22.json
python convert_train_code.py --input_file train-00122_problem_info_2.json
python convert_train_code.py --input_file train-00122_problem_info_4.json
python convert_train_code.py --input_file train-00122_problem_info_9.json
python convert_train_code.py --input_file train-00122_problem_info_13.json
python convert_train_code.py --input_file train-00122_problem_info_14.json
python convert_train_code.py --input_file train-00122_problem_info_16.json
python convert_train_code.py --input_file train-00122_problem_info_17.json
python convert_train_code.py --input_file train-00122_problem_info_18.json
python convert_train_code.py --input_file train-00122_problem_info_19.json
python convert_train_code.py --input_file train-00122_problem_info_20.json
python convert_train_code.py --input_file train-00122_problem_info_23.json
python convert_train_code.py --input_file train-00122_problem_info_24.json
python convert_train_code.py --input_file train-00122_problem_info_25.json
python convert_train_code.py --input_file train-00122_problem_info_26.json
python convert_train_code.py --input_file train-00122_problem_info_31.json
python convert_train_code.py --input_file train-00123_problem_info_1.json
python convert_train_code.py --input_file train-00123_problem_info_9.json
python convert_train_code.py --input_file train-00123_problem_info_18.json
python convert_train_code.py --input_file train-00123_problem_info_21.json
python convert_train_code.py --input_file train-00123_problem_info_23.json
python convert_train_code.py --input_file train-00123_problem_info_25.json
python convert_train_code.py --input_file train-00123_problem_info_26.json
python convert_train_code.py --input_file train-00123_problem_info_31.json
python convert_train_code.py --input_file train-00124_problem_info_1.json
python convert_train_code.py --input_file train-00124_problem_info_4.json
python convert_train_code.py --input_file train-00124_problem_info_10.json
python convert_train_code.py --input_file train-00124_problem_info_15.json
python convert_train_code.py --input_file train-00124_problem_info_17.json
python convert_train_code.py --input_file train-00125_problem_info_0.json
python convert_train_code.py --input_file train-00125_problem_info_1.json
python convert_train_code.py --input_file train-00125_problem_info_4.json
python convert_train_code.py --input_file train-00125_problem_info_9.json
python convert_train_code.py --input_file train-00125_problem_info_10.json
python convert_train_code.py --input_file train-00125_problem_info_11.json
python convert_train_code.py --input_file train-00125_problem_info_14.json
python convert_train_code.py --input_file train-00125_problem_info_16.json
python convert_train_code.py --input_file train-00125_problem_info_18.json
python convert_train_code.py --input_file train-00126_problem_info_1.json
python convert_train_code.py --input_file train-00126_problem_info_3.json
python convert_train_code.py --input_file train-00126_problem_info_4.json
python convert_train_code.py --input_file train-00126_problem_info_6.json
python convert_train_code.py --input_file train-00126_problem_info_7.json
python convert_train_code.py --input_file train-00126_problem_info_12.json
python convert_train_code.py --input_file train-00126_problem_info_14.json
python convert_train_code.py --input_file train-00126_problem_info_16.json
python convert_train_code.py --input_file train-00126_problem_info_17.json
python convert_train_code.py --input_file train-00126_problem_info_22.json
python convert_train_code.py --input_file train-00127_problem_info_0.json
python convert_train_code.py --input_file train-00127_problem_info_2.json
python convert_train_code.py --input_file train-00127_problem_info_5.json
python convert_train_code.py --input_file train-00127_problem_info_8.json
python convert_train_code.py --input_file train-00127_problem_info_13.json
python convert_train_code.py --input_file train-00127_problem_info_14.json
python convert_train_code.py --input_file train-00127_problem_info_15.json
python convert_train_code.py --input_file train-00127_problem_info_16.json
python convert_train_code.py --input_file train-00127_problem_info_18.json
python convert_train_code.py --input_file train-00127_problem_info_20.json
python convert_train_code.py --input_file train-00127_problem_info_21.json
python convert_train_code.py --input_file train-00127_problem_info_22.json
python convert_train_code.py --input_file train-00127_problem_info_23.json
python convert_train_code.py --input_file train-00127_problem_info_25.json
python convert_train_code.py --input_file train-00127_problem_info_26.json
python convert_train_code.py --input_file train-00127_problem_info_28.json
python convert_train_code.py --input_file train-00127_problem_info_29.json
python convert_train_code.py --input_file train-00127_problem_info_30.json
python convert_train_code.py --input_file train-00127_problem_info_32.json
